version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_tutorial:/var/jenkins_home
volumes:
  jenkins_tutorial:
